import type { Metadata } from "next";
import "../globals.css";
import { Language } from "../model/language";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: Language };
}) {
  return (
    <html lang={locale}>
      <body>{children}</body>
    </html>
  );
}
